version: '2'

services:
  wordpress:
    depends_on:
      - db
    image: gcr.io/proudcity-1184/wp-proudcity:master-39e21f565a2f80fd80ebecd991ae7b46308f3a88
    volumes:
      - wp-proudcity-sync:/app/wordpress:nocopy # nocopy is important
      #- ./wordpress:/app/wordpress
    tty: true
    ports:
      - "8000:80"
    environment:
      AUTH_REQUIRED:
      AUTH_USERNAME:
      AUTH_PASSWORD:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_HOST: db
      #WORDPRESS_DB_PORT: "**LinkMe**"
      HOST: localhost:8000
      APP: beta
      WORDPRESS_AUTH_KEY:
      WORDPRESS_SECURE_AUTH_KEY:
      WORDPRESS_LOGGED_IN_KEY:
      WORDPRESS_NONCE_KEY:
      WORDPRESS_AUTH_SALT:
      WORDPRESS_SECURE_AUTH_SALT:
      WORDPRESS_LOGGED_IN_SALT:
      WORDPRESS_NONCE_SALT:
      STATELESS_MEDIA_KEY_FILE_PATH:
      STATELESS_MEDIA_BUCKET:
      STATELESS_MEDIA_DIRECTORY:
      PHP_MEMORY_LIMIT: 256M
      SMTP_HOST:
      SMTP_PASS:
      SMTP_USER:
      WP_REDIS_BACKEND_HOST:
      WP_REDIS_BACKEND_AUTH:
      ELASTICSEARCH_DOCS_HOST:
      ELASTICSEARCH_HOST:
      UPLOAD_MAX_FILESIZE: 25M
      # GOOGLE_GIT_TOKEN: # set this to download private repos and $WORDPRESS_PLUGINS in entrypoint.sh
      # WORDPRESSORG_PLUGINS:  # These plugins (csv of slugs) will be downloaded on container start (requires $GOOGLE_GIT_TOKEN)
      # WORDPRESS_PLUGINS:  # These plugins (git repo) will be downloaded on container start (requires $GOOGLE_GIT_TOKEN)
      # WORDPRESS_THEMES:  # These themes (git repo) will be downloaded on container start (requires $GOOGLE_GIT_TOKEN)
      WP_CACHE: 0
      WP_DEBUG: 0
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
        - 3306:3306

volumes:
  wp-proudcity-sync:
    external: true