wordpress:
  image: proudcity/wp-proudcity
  links:
   - db
  ports:
   - "8080:80"
  environment:
    DB_NAME: wordpress
    DB_USER: admin
    DB_PASS: "<pass>"
    DB_HOST: "**LinkMe**"
    DB_PORT: "**LinkMe**"
    WORDPRESS_DB_CHARSET: utf8
    WORDPRESS_DB_COLLATE:
    WORDPRESS_AUTH_KEY:
    WORDPRESS_SECURE_AUTH_KEY:
    WORDPRESS_LOGGED_IN_KEY:
    WORDPRESS_NONCE_KEY:
    WORDPRESS_AUTH_SALT:
    WORDPRESS_SECURE_AUTH_SALT:
    WORDPRESS_LOGGED_IN_SALT:
    WORDPRESS_NONCE_SALT:
    WORDPRESS_AWS_ACCESS_KEY_ID: MYACCESSKEY
    WORDPRESS_AWS_SECRET_ACCESS_KEY: MYACCESSKEY
    WORDPRESS_TABLE_PREFIX: wp_
    WORDPRESS_WPLANG: en_US
    WORDPRESS_WP_DEBUG: 
    WORDPRESS_FS_METHOD: direct
    WORDPRESS_WP_SITEURL: http://localhost:8080
    WORDPRESS_WP_HOME: http://localhost:8080
    PROUD_URL: "http://dev.proudcity.com:4000/rest/v1.1"
    PROUD_ID: "56727f1d16b99c054df3ab67"
    PROUD_CLIENT: "56727f1d16b99c054df3ab67"
    PROUD_SECRET: "1d10c218-23cb-48e2-831e-3d31bf14a820"
    URL: "http://dev.proudcity.com:8080"
db:
  image: tutum/mysql:5.5
  environment:
    MYSQL_PASS: "<pass>"