version: '2'

services:
  wordpress:
    depends_on:
      - db
    image: gcr.io/proudcity-1184/wp-proudcity:master-39e21f565a2f80fd80ebecd991ae7b46308f3a88
    volumes:
      - wordpress:/app/wordpress
    tty: true
    ports:
      - "8000:80"
    environment:
      AUTH_REQUIRED: 1
      AUTH_USERNAME: a
      AUTH_PASSWORD: b
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_HOST: db
      #WORDPRESS_DB_PORT: "**LinkMe**"
      HOST: http://localhost:8080
      APP: beta
      WORDPRESS_AUTH_KEY:
      WORDPRESS_SECURE_AUTH_KEY:
      WORDPRESS_LOGGED_IN_KEY:
      WORDPRESS_NONCE_KEY:
      WORDPRESS_AUTH_SALT:
      WORDPRESS_SECURE_AUTH_SALT:
      WORDPRESS_LOGGED_IN_SALT:
      WORDPRESS_NONCE_SALT:
      STATELESS_MEDIA_KEY_FILE_PATH:
      STATELESS_MEDIA_BUCKET:
      STATELESS_MEDIA_DIRECTORY:
      PHP_MEMORY_LIMIT: 256M
      GOOGLE_GIT_TOKEN:
      SMTP_HOST:
      SMTP_PASS:
      SMTP_USER:
      WP_REDIS_BACKEND_HOST:
      WP_REDIS_BACKEND_AUTH:
      ELASTICSEARCH_DOCS_HOST:
      ELASTICSEARCH_HOST:
      UPLOAD_MAX_FILESIZE: 25M
      # WORDPRESS_PLUGINS:  # not used in development
      # WORDPRESS_THEMES:  # not used in development
      WP_CACHE: 0
      WP_DEBUG: 0

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
        - 3306:3306

volumes:
    wordpress:
